export class Account{
  _id?:any;
  bankName?:string;
  accountNumber?:number;
  ifscCode?:string;
  firstName?:string;
  lastName?:string;
  gender?:string;
  dateOfBirth?:string;
  martialStatus?:string;
  age?:number;
  address?:string;
  pinCode?:number;
  mobileNumber?:number;
  alternateNumber?:number;
  nationality?:string;
  religion?:string;
  email?:string;
  userImage?:string;
  citizenShip?:string;
  captcha?:string
}
